### ISSUE TITLE
安装好nodejs后，127.0.0.1:3000/recorder/v1/start执行服务报错

### ISSUE THREAD

**Issue by WYongLin** [AgoraIO/Basic-Recording#24]
nodejs安装顺利，都没什么问题。

请求日志：
[root@iZbp1d7lhouczzmadqkxeyZ ~]# curl -i -X POST -H "Content-type: application/json" --data '{"appid":"8bbac01e1a0c4cf296da026e00c47fc2","channel":"6f7ds8fd67s8"}' 127.0.0.1:3000/recorder/v1/start
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 39
ETag: W/"27-AVZqv8UOgmCjnJ8GRaCVqINlECs"
Date: Mon, 27 May 2019 01:42:43 GMT
Connection: keep-alive
{"success":false,"err":"generic error"}

nodejs日志，我们自己加了一些入参打印：
/root/.pm2/logs/agora-out.log last 15 lines:
0|agora    | /recorder/v1/start 入参： {"appid":"8bbac01e1a0c4cf296da026e00c47fc2","channel":"6f7ds8fd67s8"}
0|agora    | setting mix layout...
0|agora    | joinChannel...
0|agora    | appliteDir /home/hsyun/agoraIO/record/src/sdk/bin/
0|agora    | pRecording->m_agorasdk->createChannel return result:1

/root/.pm2/logs/agora-error.log last 15 lines:
0|agora    | Error: appid is mandatory
0|agora    |     at app.post (/home/hsyun/agoraIO/server/app.js:18:15)
0|agora    |     at Layer.handle [as handle_request] (/home/hsyun/agoraIO/server/node_modules/express/lib/router/layer.js:95:5)
0|agora    |     at next (/home/hsyun/agoraIO/server/node_modules/express/lib/router/route.js:137:13)
0|agora    |     at Route.dispatch (/home/hsyun/agoraIO/server/node_modules/express/lib/router/route.js:112:3)
0|agora    |     at Layer.handle [as handle_request] (/home/hsyun/agoraIO/server/node_modules/express/lib/router/layer.js:95:5)
0|agora    |     at /home/hsyun/agoraIO/server/node_modules/express/lib/router/index.js:281:22
0|agora    |     at Function.process_params (/home/hsyun/agoraIO/server/node_modules/express/lib/router/index.js:335:12)
0|agora    |     at next (/home/hsyun/agoraIO/server/node_modules/express/lib/router/index.js:275:10)
0|agora    |     at jsonParser (/home/hsyun/agoraIO/server/node_modules/body-parser/lib/types/json.js:119:7)
0|agora    |     at Layer.handle [as handle_request] (/home/hsyun/agoraIO/server/node_modules/express/lib/router/layer.js:95:5)
0|agora    | Error: 13,with stat_code:3
0|agora    | undefined
0|agora    | Error: 13,with stat_code:3
0|agora    | undefined

appId货真价实

**Comment by WYongLin** [comment]
0|agora | pRecording->m_agorasdk->createChannel return result:1
看日志，sdk调用创建channel应该返回true的吧？应该是没什么问题。。。

**Comment by plutoless** [comment]
@WYongLin appid is mandatory应该是你前两次请求没有给appid导致的，我看最新的一次执行是成功的，但启动后因为error:13退出了，应该是频道里没人，你这边启动sdk加入对应的频道了吗？

**Comment by lavish0000** [comment]
我正面临着同样的问题。您能为我提供解决方案吗？

**Comment by lavish0000** [comment]
0|server  | setting mix layout...
0|server  | 3
0|server  | joinchannel data { key: '00674f8113126d14c66b56e4839be720d37IAApsimG4IFU+9yvBGpJMNDy7obT1ox3tHWaSZm0IPlwUtyOVW0AAAAAEADf5xBlMercXQEA6APti9td',
0|server  |   channel: 'CJ_Live_Stream_1574343820',
0|server  |   appid: '74f8113126d14c66b56e4839be720d37',
0|server  |   storagePath: '/var/www/html/Scrap-n-Scour/route/Streaming/output/02f1a7d5-4549-464f-beae-720cd5001e59' }
0|server  | joinChannel...
0|server  | appliteDir
0|server  | /var/www/html/Scrap-n-Scour/route/Streaming/record/src/sdk/bin/
0|server  | pRecording->m_agorasdk->createChannel return result:
0|server  | 1
0|server  | Error:
0|server  | 13
0|server  | ,with stat_code:
0|server  | 3
0|server  | ERROR 13

**Comment by lavish0000** [comment]
this is the error i am getting.

**Comment by plutoless** [comment]
@lavish0000  CJ_Live_Stream_1574343820 应该是这个频道没有流，你需要现有客户端加入频道推流，录制程序才可以录下来

**Comment by lavish0000** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/46993225/69547039-3e827d80-0fc3-11ea-8557-c4ab4e16c4de.png)

**Comment by lavish0000** [comment]
@plutoless , this is the code i am usinig and i have added consoles, like 1, 2, 3. I thinks that the error is coming when joining the channel because after "joinchannel data" that no logs are printed.

**Comment by lavish0000** [comment]
{
    key: '00674f8113126d14c66b56e4839be720d37IAA3axTi4uT2zAFog4q54HfYsmk1t+PJ7+/670C5YzArKJRzpj4AAAAAEABIM/xyz7/XXQEA6APLe9Zd',
   channel: 'CJ_Live_Stream_1574334029.18331261',
   appid: '74xxxxxxxxxxxxxxxxxx7',
  storagePath: '/var/www/html/scrap/route/Streaming/output/4062fb11-f630-4c3e-bef8-0e96a60675ee' 
}

**Comment by lavish0000** [comment]
and this is the data, i am giving as input while joining channel.

**Comment by plutoless** [comment]
@lavish0000  could you pls help provide your log file to me? usually this is located in the output folder.

**Comment by lavish0000** [comment]
@plutoless , I looked into the logs file, i found the error, thanks for helping.😊

**Comment by plutoless** [comment]
@lavish0000  good to know! thanks.

**Comment by BSuryakumar** [comment]
i have same issue.please share how to solve this issue

**Comment by BSuryakumar** [comment]
@lavish0000  i have same issue.please share how to solve this issue

**Comment by BSuryakumar** [comment]
> @plutoless , I looked into the logs file, i found the error, thanks for helping.😊

please share the solving solution

**Comment by lavish0000** [comment]
@BSuryakumar , in my case their was permission error, you have to give executable permission, to the file inside bin.

**Comment by lavish0000** [comment]
look into your log file, you will see the path for it, to whom you need to give permission.

**Comment by BSuryakumar** [comment]
@lavish0000 Where I find the log files????

**Comment by BSuryakumar** [comment]
I couldn't find the bin file and i don't know where the logs

how to give that permission

**Comment by BSuryakumar** [comment]
![filezilla error](https://user-images.githubusercontent.com/40198942/89763369-ffc03380-db0f-11ea-8225-9ed27f7c5da3.png)

**Comment by BSuryakumar** [comment]
![filezilla error](https://user-images.githubusercontent.com/40198942/89763633-8e34b500-db10-11ea-8c57-34214c6a5469.png)

**Comment by BSuryakumar** [comment]
> @BSuryakumar , in my case their was a permission error, you have to give executable permission, to the file inside bin.

which file i declare the permission????

**Comment by lavish0000** [comment]
for me this was the path "record/src/sdk/bin/", and inside this their was a flie, to which i gave the permission

**Comment by BSuryakumar** [comment]
![bin](https://user-images.githubusercontent.com/40198942/89775326-36547900-db25-11ea-9d23-5da16419d0b4.png)

**Comment by BSuryakumar** [comment]
> for me this was the path "record/src/sdk/bin/", and inside this their was a flie, to which i gave the permission

this is my   "record/src/sdk/bin/" path .where i declare the permission

**Comment by lavish0000** [comment]
by giving permission to agoracoreservice worked for me.

**Comment by BSuryakumar** [comment]
![outp](https://user-images.githubusercontent.com/40198942/89777559-93eac480-db29-11ea-811b-ac3959110c31.png)

**Comment by BSuryakumar** [comment]
this is my output folder.Where i get the video files?????

**Comment by lavish0000** [comment]
ok, so look into the logs file, you will found the error

**Comment by BSuryakumar** [comment]
i have no error in my log .
![ou](https://user-images.githubusercontent.com/40198942/89778845-d1e8e800-db2b-11ea-851f-2c0657c501b8.png)

**Comment by BSuryakumar** [comment]
can you share the app.js and recordmanager.js????

**Comment by BSuryakumar** [comment]
can you solve this issue.payment also providing this task.please help from this task.contact us xvrraja44@gmail.com

**Comment by plutoless** [comment]
looks like your appid is empty? @BSuryakumar

**Comment by BSuryakumar** [comment]
No plutoless  .I hide the app id key for the post

**Comment by BSuryakumar** [comment]
can you help for this issue???

**Comment by plutoless** [comment]
@BSuryakumar telecall <- is this your project? your project has token feature on. you will need to provide a token for your recording service when joining channel. I just checked the backend, none of your recording process managed to join the channel.

**Comment by mahmuddin** [comment]
I have a same problem.. It's my log


 agora-recording > setting mix layout...                                                                                                                         
agora-recording > joinChannel...                                                                                                                                
agora-recording > appliteDir                                                                                                                                    
agora-recording > /var/www/html/recorder/record/src/sdk/bin/                                                                                                    
agora-recording > pRecording->m_agorasdk->createChannel return result:1                                                                                         
agora-recording > Error: 13,with stat_code:3                                                                                                                    
agora-recording > sdk stopped due to err code: 13 stat: 3                                                                                                       
agora-recording > stop recorder 7295b79344834970948755a409d9bc0c stream_1_9500053 16a00a27-82f9-4174-abf9-165d05761e04                                          
agora-recording > Error: recorder not exists                                                                                                                    
agora-recording >     at RecordManager.onCleanup (/var/www/html/recorder/server/recordManager.js:171:19)                                                        
agora-recording >     at AgoraRecordSdk.<anonymous> (/var/www/html/recorder/server/recordManager.js:78:18)                                                      
agora-recording >     at AgoraRecordSdk.emit (events.js:412:35)                                                                                                 
agora-recording >     at Immediate.<anonymous> (/var/www/html/recorder/record/AgoraRecordSdk.js:18:18)                                                         
agora-recording >     at processImmediate (internal/timers.js:464:21)      

I have success installed on my local computer, but error like this in production server. Please help..

**Comment by plutoless** [comment]
please double check if you have provided your token/appid correctly.

**Comment by mahmuddin** [comment]
I fix it with change permission for file AgoraCoreService:

cd record/src/sdk/bin/

chmod 777 AgoraCoreService

Thanks...
